// ==========================================================================
// 📥 《奔驰在路上的汗水》核心课文数据集 + 教师专属逐段赏析 - data.js
// ==========================================================================

const lessonTitle = [
  ["奔驰", "bēn chí", "run quickly / speed", "memecut / berlari kencang"],
  ["在", "zài", "on", "di / di atas"],
  ["路上", "lù shàng", "on the road", "jalan / di perjalanan"],
  ["的", "de", "particle", "yang"],
  ["汗水", "hàn shuǐ", "sweat", "peluh / air peluh"]
];

const lessonData = [
    // 第 1 段：震撼弹
    ["震撼弹", "zhèn hàn dàn", "shocking bombshell", "kejutan besar / bom jangka"],
    ["\n", "", "", ""],
    ["没有", "méi yǒu", "there is no", "tidak ada / tanpa"],
    ["硝烟", "xiāo yān", "gunsmoke", "asap meriam / asap senapang"],
    ["的", "de", "particle", "yang"],
    ["战争", "zhàn zhēng", "war", "peperangan / perang"],
    ["\n", "", "", ""],
    ["悄然", "qiǎo rán", "quietly / silently", "secara senyap / diam-diam"],
    ["降临", "jiàng lín", "befall / arrive", "datang melanda / menjelma"],
    ["\n", "", "", ""],
    ["回到", "huí dào", "return to", "pulang ke / kembali ke"],
    ["家里", "jiā lǐ", "home / inside the house", "rumah / dalam rumah"],
    ["\n", "", "", ""],
    ["他", "tā", "he", "dia"],
    ["从", "cóng", "from", "dari"],
    ["公事包", "gōng shì bāo", "briefcase", "beg kerja / beg bimbit"],
    ["\n", "", "", ""],
    ["拿出了", "ná chū le", "took out", "mengeluarkan"],
    ["公司", "gōng sī", "company", "syarikat"],
    ["给", "gěi", "give", "bagi / memberi / kepada"],
    ["他", "tā", "him", "dia"],
    ["的", "de", "particle", "yang"],
    ["信", "xìn", "letter", "surat"],
    ["\n", "", "", ""],
    ["给", "gěi", "to / for", "kepada / buat"],
    ["家人", "jiā rén", "family members", "ahli keluarga"],
    ["扔出了", "rēng chū le", "threw out / dropped", "melemparkan / memberikan"],
    ["震撼弹", "zhèn hàn dàn", "bombshell", "kejutan yang amat besar"],
    ["。", "", "", ""],

    ["\n", "", "", ""], // 👈 第 2 段：考验与挑战

    ["考验", "kǎo yàn", "trial / ordeal", "cabaran / ujian"],
    ["与", "yǔ", "and", "dan"],
    ["挑战", "tiǎo zhàn", "challenge", "cabaran"],
    ["\n", "", "", ""],
    ["长长", "cháng cháng", "long", "panjang / yang panjang"],
    ["的", "de", "particle", "yang"],
    ["账单", "zhàng dān", "bill", "bil / tunggakan bayaran"],
    ["，", "", "", ""],
    ["\n", "", "", ""],
    ["让", "ràng", "make / cause", "membuatkan / menyebabkan"],
    ["他", "tā", "him", "dia"],
    ["眉头", "méi tóu", "brows", "dahi / kening"],
    ["上", "shàng", "on", "atas"],
    ["岁月", "suì yuè", "years / time", "masa / usia / usia tua"],
    ["的", "de", "particle", "punya"],
    ["印记", "yìn jì", "imprint / mark", "kesan / tanda"],
    ["\n", "", "", ""],
    ["又", "yòu", "again", "lagi / bertambah"],
    ["增添", "zēng tiān", "add / increase", "menambah / meningkatkan"],
    ["几道", "jǐ dào", "several (measure word for lines/wrinkles)", "beberapa jalur"],
    ["\n", "", "", ""],
    ["思前想后", "sī qián xiǎng hòu", "ponder over / consider thoroughly", "berfikir masak-masak / mempertimbangkan perkara"],
    ["，", "", "", ""],
    ["\n", "", "", ""],
    ["毅然", "yì rán", "resolutely", "dengan tekad / tabah"],
    ["戴起", "dài qǐ", "put on (hat/helmet)", "memakai"],
    ["头盔", "tóu kuī", "helmet", "topi keledar"],
    ["，", "", "", ""],
    ["骑上", "qí shàng", "ride on", "menunggang"],
    ["摩托车", "mó tuō chē", "motorcycle", "motosikal"],
    ["\n", "", "", ""],
    ["把", "bǎ", "structural particle", ""],
    ["汗水", "hàn shuǐ", "sweet", "air peluh / peluh"],
    ["挥洒", "huī sǎ", "shed / sprinkle", "mencurahkan / menyembur"],
    ["于", "yú", "on / at", "di / pada"],
    ["路上", "lù shàng", "on the road", "jalan raya"],
    ["\n", "", "", ""],
    ["肩负起", "jiān fù qǐ", "shoulder / take up the burden", "memikul / menggalas"],
    ["\n", "", "", ""],
    ["让", "ràng", "let / make", "membiarkan / memastikan"],
    ["门户", "mén hù", "households / doors", "pintu rumah / pelanggan"],
    ["及时", "jí shí", "in time / timely", "tepat pada masanya"],
    ["吃上", "chī shàng", "get to eat", "dapat makan"],
    ["热腾腾", "rè téng téng", "piping hot", "panas-panas / berasap panas"],
    ["美食", "měi shí", "delicious food / delicacy", "makanan lazat"],
    ["的", "de", "particle", "yang"],
    ["重任", "zhòng rèn", "heavy responsibility / mission", "tanggungjawab berat / amanah"],
    ["。", "", "", ""],

    ["\n", "", "", ""], // 👈 第 3 段：奔波

    ["奔波", "bēn bō", "rush about / rush around", "ke sana ke mari / membanting tulang"],
    ["\n", "", "", ""],
    ["阳光明媚", "yáng guāng míng mèi", "bright and beautiful sunshine", "cahaya matahari yang cerah"],
    ["时", "shí", "when", "apabila / sewaktu"],
    ["，", "", "", ""],
    ["\n", "", "", ""],
    ["无惧", "wú jù", "fearless / no fear", "tidak takut / tanpa ragu"],
    ["骄阳", "jiāo yáng", "blazing sun", "matahari terik"],
    ["的", "de", "particle", "punya / yang"],
    ["炽烈", "chì liè", "fierce / scorching", "membara / sangat terik"],
    ["；", "", "", ""],
    ["\n", "", "", ""],
    ["疾风骤雨", "jí fēng zhòu yǔ", "gale and torrential rain", "angin kencang dan hujan lebat"],
    ["时", "shí", "when", "apabila / sewaktu"],
    ["，", "", "", ""],
    ["\n", "", "", ""],
    ["无畏", "wú wèi", "fearless / undaunted", "tidak gentar / berani menghadapi"],
    ["风雨", "fēng yǔ", "wind and rain", "ribut / angin dan hujan"],
    ["的", "de", "particle", "punya / yang"],
    ["猛烈", "měng liè", "fierce / violent", "hebat / kuat / dahsyat"],
    ["，", "", "", ""],
    ["\n", "", "", ""],
    ["依旧", "yī jiù", "still / as before", "masih / tetap seperti biasa"],
    ["挺直", "tǐng zhí", "straighten (back)", "menegakkan / meluruskan"],
    ["背脊", "bèi jí", "backbone / spine", "tulang belakang / belakang badan"],
    ["，", "", "", ""],
    ["\n", "", "", ""],
    ["穿梭", "chuān suō", "shuttle / weave through", "berulang-alik / menyusup"],
    ["于", "yú", "in / between", "di / dalam"],
    ["车水马龙", "chē shuǐ mǎ lóng", "heavy traffic", "kesesakan lalu lintas / jalan raya yang sibuk"],
    ["的", "de", "particle", "yang"],
    ["大街", "dà jiē", "main street", "jalan besar"],
    ["和", "hé", "and", "dan"],
    ["小巷", "xiǎo xiàng", "alley / lane", "lorong kecil"],
    ["；", "", "", ""],
    ["\n", "", "", ""],
    ["兢兢业业", "jīng jīng yè yè", "cautious and conscientious / dedicated", "dengan tekun dan dedikasi / cermat dan setia"],
    ["，", "", "", ""],
    ["\n", "", "", ""],
    ["把", "bǎ", "structural particle", ""],
    ["食物", "shí wù", "food", "makanan"],
    ["保温袋", "bǎo wēn dài", "insulated bag / thermal bag", "beg penebat haba / beg simpan panas"],
    ["里", "lǐ", "inside", "dalam / di dalam"],
    ["的", "de", "particle", "punya / yang"],
    ["餐食", "cān shí", "meals / food", "makanan / hidangan"],
    ["\n", "", "", ""],
    ["稳当地", "wěn dàng de", "steadily / safely", "dengan stabil / dengan selamat / dengan cermat"],
    ["送达", "sòng dá", "deliver to", "menyampaikan / menghantar sampai ke"],
    ["订户", "dì hù", "subscriber / customer", "pelanggan / pemesan"],
    ["的", "de", "particle", "punya"],
    ["手上", "shǒu shàng", "hands / into hands", "tangan / ke tangan"],
    ["。", "", "", ""],

    ["\n", "", "", ""], // 👈 第 4 段：坚持

    ["坚持", "jiān chí", "persist / insist on", "ketabahan / kecekalan / terus berusaha"],
    ["\n", "", "", ""],
    ["他", "tā", "he", "Dia"],
    ["深知", "shēn zhī", "know well / deeply appreciate", "amat mengetahui / sangat sedar"],
    ["，", "", "", ""],
    ["准时", "zhǔn shí", "on time / punctual", "tepat pada masanya / amanah masa"],
    ["是", "shì", "is", "adalah"],
    ["承诺", "chéng nuò", "promise / commitment", "janji / komitmen"],
    ["；", "", "", ""],
    ["\n", "", "", ""],
    ["偶尔", "ǒu ěr", "occasionally / once in a while", "sekali-sekala / kadangkala"],
    ["因为", "yīn wèi", "because", "kerana"],
    ["身体状态不佳", "shēn tǐ zhuàng tài bù jiā", "unwell / poor physical condition", "kesihatan kurang baik / badan kurang sihat"],
    ["或", "huò", "or", "atau"],
    ["路况", "lù kuàng", "road condition", "keadaan jalan raya"],
    ["，", "", "", ""],
    ["\n", "", "", ""],
    ["而", "ér", "and thereby / leading to", "lalu / maka menyebabkan"],
    ["延误", "yán wù", "delay", "terlewat / tertangguh"],
    ["，", "", "", ""],
    ["\n", "", "", ""],
    ["招致", "zhāo zhì", "incur / bring about", "mengundang / menyebabkan datangnya"],
    ["订户", "dì hù", "customer", "pelanggan"],
    ["的", "de", "particle", "punya"],
    ["埋怨", "mái yuàn", "complaint / blame", "rungutan / luahan rasa tidak puas hati"],
    ["，", "", "", ""],
    ["\n", "", "", ""],
    ["满肚子", "mǎn dù zi", "stomach full of / bellyful of", "sepenuh perut / penuh dengan"],
    ["的", "de", "particle", "yang"],
    ["苦楚", "kǔ chǔ", "suffering / pain / misery", "kesedihan / penderitaan / kepahitan"],
    ["，", "", "", ""],
    ["\n", "", "", ""],
    ["只能", "zhǐ néng", "could only", "hanya mampu / hanya boleh"],
    ["化作", "huà zuò", "turn into / transform into", "menjadi / bertukar menjadi"],
    ["一声", "yì shēng", "a sound of / a single", "satu"],
    ["叹息", "tàn xī", "sigh", "keluhan"],
    ["。", "", "", ""],

    ["\n", "", "", ""], // 👈 第 5 段：无私奉献与追逐

    ["他", "tā", "he", "Dia"],
    ["在", "zài", "in", "di / dalam"],
    ["风里雨里", "fēng lǐ yǔ lǐ", "through wind and rain", "redah angin dan hujan / susah payah"],
    ["，", "", "", ""],
    ["风尘仆仆", "fēng chén pú pú", "travel-worn / travel-weary", "penat lelah di perjalanan / bergelumang debu"],
    ["，", "", "", ""],
    ["\n", "", "", ""],
    ["分不清", "fēn bù qīng", "cannot distinguish", "tidak dapat membedakan"],
    ["是", "shì", "is", "adalah"],
    ["汗", "hàn", "sweat", "peluh"],
    ["是", "shì", "is", "atau"],
    ["雨", "yǔ", "rain", "hujan"],
    ["，", "", "", ""],
    ["\n", "", "", ""],
    ["无暇", "wú xiá", "have no time to", "tidak ada masa untuk / tidak sempat"],
    ["擦拭", "cā shì", "wipe", "mengelap / mengesat"],
    ["，", "", "", ""],
    ["依旧", "yī jiù", "still", "tetap / masih"],
    ["抖擞精神", "dǒu sǒu jīng shén", "rouse one's spirit", "bersemangat tinggi / bangkitkan semangat"],
    ["；", "", "", ""],
    ["\n", "", "", ""],
    ["尽管", "jǐn guån", "even though / although", "walaupun / biarpun"],
    ["容颜", "róng yán", "countenance / face appearance", "wajah / raut wajah"],
    ["憔悴了", "qiáo cuì le", "haggard / worn out", "cengkung / lesu / cemas"],
    ["，", "", "", ""],
    ["\n", "", "", ""],
    ["身心", "shēn xīn", "body and mind", "jasmani dan rohani / tubuh dan jiwa"],
    ["疲惫了", "pí bèi le", "exhausted / tired out", "keletihan / teramat penat"],
    ["，", "", "", ""],
    ["\n", "", "", ""],
    ["也要", "yě yào", "also must", "tetap perlu / harus juga"],
    ["规矩地", "guī ju de", "properly / following rules", "dengan berdisiplin / mengikut peraturan / dengan patuh"],
    ["履行", "lǚ xíng", "fulfill / carry out", "menjalankan / menunaikan"],
    ["职责", "zhí zé", "duty / responsibility", "tanggungjawab / tugas"],
    ["，", "", "", ""],
    ["\n", "", "", ""],
    ["继续", "jì xù", "continue", "meneruskan"],
    ["与", "yǔ", "with", "dengan"],
    ["时间", "shí jiān", "time", "masa"],
    ["追逐", "zhuī zhú", "chase / pursue", "kejar-mengejar / mengejar"],
    ["的", "de", "particle", "yang"],
    ["游戏", "yóu xì", "game", "permainan"],
    ["。", "", "", ""],

    ["\n", "", "", ""], // 👈 第 6 段：温暖与动力

    ["温暖", "wēn nuǎn", "warmth", "Kehangatan"],
    ["与", "yǔ", "and", "dan"],
    ["动力", "dòng lì", "driving force / motivation", "motivasi / dorongan / kekuatan"],
    ["\n", "", "", ""],
    ["一份", "yí fèn", "a (measure word for meal/gift)", "sepotong / sebahagian / senaskah"],
    ["暖意融融", "nuǎn yì róng róng", "full of warmth", "yang penuh kehangatan / mesra"],
    ["的", "de", "particle", "yang"],
    ["餐点", "cān diàn", "meal / snack", "hidangan makanan / makanan"],
    ["，", "", "", ""],
    ["\n", "", "", ""],
    ["一罐", "yí guàn", "a can of", "setin"],
    ["沁人心脾", "qìn rén xīn pí", "refreshing / gladdening the heart", "menyegarkan jiwa / meresap ke dalam hati"],
    ["的", "de", "particle", "yang"],
    ["饮料", "yǐn liào", "drink / beverage", "minuman"],
    ["，", "", "", ""],
    ["\n", "", "", ""],
    ["一声声", "yì shēng shēng", "sound after sound of", "ungkapan demi ungkapan / ucapan berulang kali"],
    ["真诚", "zhēn chéng", "sincere", "ikhlas / jujur"],
    ["的", "de", "particle", "yang"],
    ["道谢", "dào xiè", "thanks / expression of gratitude", "ucapan terima kasih"],
    ["，", "", "", ""],
    ["\n", "", "", ""],
    ["家人", "jiā rén", "family", "ahli keluarga"],
    ["熟睡", "shú shuì", "fast asleep", "tidur nyenyak"],
    ["的", "de", "particle", "punya"],
    ["面容", "miàn róng", "face / look", "wajah / raut wajah"],
    ["和", "hé", "and", "dan"],
    ["贴心", "tiē xīn", "considerate / intimate", "ambil berat / intim / prihatin"],
    ["的", "de", "particle", "yang"],
    ["关爱", "guān ài", "care and love", "kasih sayang / perhatian"],
    ["，", "", "", ""],
    ["\n", "", "", ""],
    ["是", "shì", "are", "adalah"],
    ["这些", "zhè xiē", "these", "hari-hari / semua"],
    ["日子", "rì zi", "days / time", "hari / masa"],
    ["里", "lǐ", "in", "dalam"],
    ["\n", "", "", ""],
    ["他", "tā", "him", "dia"],
    ["最大", "zuì dà", "the greatest", "paling besar"],
    ["的", "de", "particle", "punya"],
    ["慰藉", "wèi jiè", "consolation / comfort", "sumber penghibur / kelegaan"],
    ["与", "yǔ", "and", "dan"],
    ["动力", "dòng lì", "motivation / power", "dorongan / kekuatan"],
    ["。", "", "", ""],

    ["\n", "", "", ""], // 👈 第 7 段：希冀与社会升华

    ["希冀", "xī jì", "hope / aspiration", "Harapan / impian"],
    ["\n", "", "", ""],
    ["落寞", "luò mò", "lonely / desolate", "kesepian / kelesuan jiwa"],
    ["、", "", "", ""],
    ["徘徊", "pái huái", "pace back and forth", "buntu / terawang-awang"],
    ["、", "", "", ""],
    ["焦虑", "jiāo lǜ", "anxiety / worried", "keberangan / kerisauan / kebimbangan"],
    ["不复存在", "bú fù cún zài", "no longer exist", "tidak wujud lagi / lenyap"],
    ["，", "", "", ""],
    ["\n", "", "", ""],
    ["他", "tā", "he", "dia"],
    ["奔驰", "bēn chí", "speeding / rushing", "memecut / berlari kencang"],
    ["于", "yú", "on", "di / atas"],
    ["路上", "lù shàng", "on the road", "jalan raya"],
    ["的", "de", "particle", "yang"],
    ["汗水", "hàn shuǐ", "sweat", "air peluh"],
    ["\n", "", "", ""],
    ["不会", "bú huì", "will not", "tidak akan"],
    ["白费", "bái fèi", "be in vain / wasted", "sia-sia / terbuang begitu sahaja"],
    ["。", "", "", ""],
    ["\n", "", "", ""],
    ["他", "tā", "he", "Dia"],
    ["祈愿", "qí yuàn", "pray / wish", "berdoa / berharap agar"],
    ["人们", "rén men", "people", "orang ramai / masyarakat"],
    ["，", "", "", ""],
    ["\n", "", "", ""],
    ["因为", "yīn wèi", "because of", "kerana"],
    ["关怀", "guān huái", "care / concern", "keprihatinan / ambil berat"],
    ["，", "", "", ""],
    ["\n", "", "", ""],
    ["彼此", "bǐ cǐ", "each other", "satu sama lain"],
    ["更", "gèng", "more", "lebih / semakin"],
    ["愿意", "yuàn yì", "willing to", "sudi / rela"],
    ["释出", "shì chū", "release / show", "menunjukkan / menghulurkan"],
    ["善意", "shàn yì", "goodwill / kindness", "niat baik / kebaikan"],
    ["；", "", "", ""],
    ["\n", "", "", ""],
    ["因为", "yīn wèi", "because of", "kerana"],
    ["包容", "bāo róng", "tolerance / inclusion", "sifat bertolak ansur / toleransi"],
    ["，", "", "", ""],
    ["\n", "", "", ""],
    ["大家", "dà jiā", "everyone", "semua orang"],
    ["携手同心", "xié shǒu tóng xīn", "join hands and work together", "bergandeng bahu dan sehati sejiwa"],
    ["，", "", "", ""],
    ["\n", "", "", ""],
    ["跨越", "kuà yuè", "stride across / leap over", "merentasi / melampaui"],
    ["焦躁", "jiāo zào", "impatient / irritable", "kegelisahan / sifat terburu-buru"],
    ["的", "de", "particle", "yang"],
    ["隔阂", "gé hé", "barrier / estrangement", "jurang / sempadan pemisah"],
    ["，", "", "", ""],
    ["\n", "", "", ""],
    ["一同", "yì tóng", "together", "bersama-sama"],
    ["迈向", "mài xiàng", "stride towards", "melangkah menuju ke"],
    ["\n", "", "", ""],
    ["繁荣昌盛", "fán róng chāng shèng", "prosperous / thriving", "keamanan dan kemakmuran / kegemilangan"],
    ["，", "", "", ""],
    ["\n", "", "", ""],
    ["更", "gèng", "more", "lebih / semakin"],
    ["具", "jù", "possess / have", "mempunyai / memiliki"],
    ["同理心", "tóng lǐ xīn", "empathy", "sifat empati / memahami perasaan orang lain"],
    ["的", "de", "particle", "yang"],
    ["社会", "shè huì", "society", "masyarakat"]
];

const lessonAppreciation = [
  "【第1段：坏消息来了】一开头就告诉我们发生大事了。虽然没有真正的战争，但是爸爸拿到了公司的信（可能被开除/减薪），这对全家人来说是一个很大的打击（Kejutan besar）。",
  "【第2段：伟大的爸爸】看到长长的账单（Bills），爸爸虽然很压力、很烦恼，但他没有放弃。为了家庭，他勇敢地决定（毅然）戴上头盔去驾摩托车，当起送餐员（Food delivery rider），撑起这个家。",
  "【第3段：送餐员的辛苦】这一段写爸爸工作时多么辛苦。不管是大太阳（骄阳）还是下大雨（暴雨），马路上车子非常多（车水马龙），他都很认真、很安全地把热热的食物送到顾客（Customers）手上。",
  "【第4段：受委屈的时候】爸爸知道‘准时’是他的责任（Janji）。但是有时候因为身体不舒服或者塞车（Traffic jem）迟到了，被顾客骂（埋怨），他心里觉得很委屈、很难过，也只能自己偷偷叹气。",
  "【第5段：和时间赛跑】爸爸整身湿透了，分不清是汗水还是雨水。虽然脸憔悴了、身体也非常累（疲惫），但他还是很专业，跟着交通规则，继续在马路上像‘和时间玩追逐游戏’一样拼命送餐。",
  "【第6段：爸爸的动力】这一段写什么东西让爸爸坚持下去？就是顾客拿到食物时的一声‘谢谢’、顾客送的一罐冷饮，还有回到家看到家人睡得很香。这些贴心的爱，就是爸爸最大的安慰和动力（Motivation）。",
  "【第7段：最好的愿望】最后，文章的主题变伟大了。爸爸希望他的汗水没有白费，他也希望通过自己的努力，让社会上的人变得更善良、更懂得互相关心、更有同理心（Empathy，懂得站在别人的角度想），大家一起把社会变得更美好。"
];
