const lessonTitle = "奔驰在路上的汗水";

const lessonData = [
    // ===== 第一节 =====
    ["震撼弹", "zhèn hàn dàn", "Shock bomb", "Bom kejutan"],
    ["<br>", "", "", ""],
    ["没有", "méi yǒu", "Without", "Tanpa"],
    ["硝烟", "xiāo yān", "gunpowder smoke", "asap bedil"],
    ["的", "de", "", ""],
    ["战争", "zhàn zhēng", "war", "peperangan"],
    ["<br>", "", "", ""],
    ["悄然", "qiǎo rán", "quietly", "secara senyap"],
    ["降临", "jiàng lín", "descended", "tiba"],
    ["<br>", "", "", ""],
    ["回到", "huí dào", "Returned", "Pulang ke"],
    ["家里", "jiā lǐ", "home", "rumah"],
    ["<br>", "", "", ""],
    ["他", "tā", "He", "Dia"],
    ["从", "cóng", "from", "dari"],
    ["公事包", "gōng shì bāo", "briefcase", "beg bimbit"],
    ["<br>", "", "", ""],
    ["拿出", "ná chū", "took out", "mengeluarkan"],
    ["了", "le", "", ""],
    ["公司", "gōng sī", "company", "syarikat"],
    ["给", "gěi", "to", "kepada"],
    ["他的", "tā de", "his", "dia punya"],
    ["信", "xìn", "letter", "surat"],
    ["<br>", "", "", ""],
    ["给", "gěi", "to", "kepada"],
    ["家人", "jiā rén", "family", "keluarga"],
    ["<br>", "", "", ""],
    ["扔出", "rēng chū", "threw", "melemparkan"],
    ["了", "le", "", ""],
    ["震撼弹", "zhèn hàn dàn", "shock bomb", "bom kejutan"],

    ["\n", "", "", ""], // 👈 第一节 → 第二节

    // ===== 第二节 =====
    ["考验", "kǎo yàn", "Test", "Ujian"],
    ["与", "yǔ", "and", "dan"],
    ["挑战", "tiǎo zhàn", "Challenge", "Cabaran"],
    ["<br>", "", "", ""],
    ["长长", "cháng cháng", "Long", "Panjang"],
    ["的", "de", "", ""],
    ["账单", "zhàng dān", "bills", "bil"],
    ["<br>", "", "", ""],
    ["让", "ràng", "made", "membuatkan"],
    ["他", "tā", "him", "dia"],
    ["眉头上", "méi tóu shàng", "on his forehead", "di dahinya"],
    ["<br>", "", "", ""],
    ["岁月", "suì yuè", "time", "usia"],
    ["的", "de", "", ""],
    ["印记", "yìn jì", "marks", "tanda"],
    ["<br>", "", "", ""],
    ["又", "yòu", "again", "lagi"],
    ["增添", "zēng tiān", "added", "bertambah"],
    ["几道", "jǐ dào", "a few lines", "beberapa garis"],
    ["<br>", "", "", ""],
    ["思前", "sī qián", "Think before", "Fikir dahulu"],
    ["想后", "xiǎng hòu", "think after", "fikir kemudian"],
    ["<br>", "", "", ""],
    ["毅然", "yì rán", "resolutely", "dengan tekad"],
    ["戴起", "dài qǐ", "put on", "memakai"],
    ["头盔", "tóu kuī", "helmet", "topi keledar"],
    ["<br>", "", "", ""],
    ["骑上", "qí shàng", "mounted", "menaiki"],
    ["摩托车", "mó tuō chē", "motorcycle", "motorsikal"],
    ["<br>", "", "", ""],
    ["把", "bǎ", "", ""],
    ["汗水", "hàn shuǐ", "sweat", "peluh"],
    ["挥洒", "huī sǎ", "sprinkled", "mencurahkan"],
    ["于", "yú", "on", "di"],
    ["路上", "lù shàng", "the road", "jalan"],
    ["<br>", "", "", ""],
    ["肩负", "jiān fù", "Shouldered", "Memikul"],
    ["起", "qǐ", "", ""],
    ["<br>", "", "", ""],
    ["让", "ràng", "to deliver", "agar"],
    ["门户", "mén hù", "every door", "setiap pintu"],
    ["及时", "jí shí", "on time", "tepat pada masanya"],
    ["<br>", "", "", ""],
    ["吃上", "chī shàng", "get to eat", "mendapat"],
    ["热腾腾", "rè téng téng", "steaming hot", "yang panas"],
    ["的", "de", "", ""],
    ["美食", "měi shí", "delicious food", "makanan"],
    ["的", "de", "", ""],
    ["重任", "zhòng rèn", "heavy responsibility", "tanggungjawab berat"],

    ["\n", "", "", ""], // 👈 第二节 → 第三节

    // ===== 第三节 =====
    ["奔波", "bēn bō", "Rush about", "Membanting tulang"],
    ["<br>", "", "", ""],
    ["阳光", "yáng guāng", "Sunlight", "Cahaya matahari"],
    ["明媚", "míng mèi", "bright", "cerah"],
    ["时", "shí", "when", "ketika"],
    ["<br>", "", "", ""],
    ["无惧", "wú jù", "fearless", "tidak takut"],
    ["骄阳", "jiāo yáng", "scorching sun", "matahari terik"],
    ["的", "de", "", ""],
    ["炽烈", "chì liè", "scorching", "terik"],
    ["<br>", "", "", ""],
    ["疾风", "jí fēng", "Strong wind", "Angin kencang"],
    ["骤雨", "zhòu yǔ", "sudden rain", "hujan lebat"],
    ["时", "shí", "when", "ketika"],
    ["<br>", "", "", ""],
    ["无畏", "wú wèi", "undaunted", "tidak gentar"],
    ["风雨", "fēng yǔ", "wind and rain", "hujan dan angin"],
    ["的", "de", "", ""],
    ["猛烈", "měng liè", "violent", "lebat"],
    ["<br>", "", "", ""],
    ["依旧", "yī jiù", "still", "tetap"],
    ["挺直", "tǐng zhí", "straightened", "menegakkan"],
    ["背脊", "bèi jǐ", "back", "tulang belakang"],
    ["<br>", "", "", ""],
    ["穿梭", "chuān suō", "Shuttling", "Menyusuri"],
    ["于", "yú", "through", "di"],
    ["<br>", "", "", ""],
    ["车水马龙", "chē shuǐ mǎ lóng", "heavy traffic", "kesesakan lalu lintas"],
    ["的", "de", "", ""],
    ["大街", "dà jiē", "main streets", "jalan besar"],
    ["和", "hé", "and", "dan"],
    ["小巷", "xiǎo xiàng", "alleys", "lorong kecil"],
    ["<br>", "", "", ""],
    ["兢兢", "jīng jīng", "careful", "tekun"],
    ["业业", "yè yè", "diligent", "bersungguh"],
    ["<br>", "", "", ""],
    ["把", "bǎ", "", ""],
    ["食物", "shí wù", "food", "makanan"],
    ["保温袋", "bǎo wēn dài", "insulated bag", "beg penebat haba"],
    ["里", "lǐ", "inside", "dalam"],
    ["的", "de", "", ""],
    ["餐食", "cān shí", "meals", "hidangan"],
    ["<br>", "", "", ""],
    ["稳当", "wěn dāng", "steadily", "dengan selamat"],
    ["地", "de", "", ""],
    ["送达", "sòng dá", "delivered", "dihantar"],
    ["<br>", "", "", ""],
    ["订户", "dìng hù", "customers", "pelanggan"],
    ["的", "de", "", ""],
    ["手上", "shǒu shàng", "hands", "tangan"],

    ["\n", "", "", ""], // 👈 第三节 → 第四节

    // ===== 第四节 =====
    ["坚持", "jiān chí", "Persistence", "Ketabahan"],
    ["<br>", "", "", ""],
    ["他", "tā", "He", "Dia"],
    ["深知", "shēn zhī", "knows well", "sedar"],
    ["<br>", "", "", ""],
    ["准时", "zhǔn shí", "punctuality", "tepat masa"],
    ["是", "shì", "is", "ialah"],
    ["承诺", "chéng nuò", "a promise", "janji"],
    ["<br>", "", "", ""],
    ["偶尔", "ǒu ěr", "Sometimes", "Kadang-kadang"],
    ["因为", "yīn wèi", "because of", "kerana"],
    ["<br>", "", "", ""],
    ["身体", "shēn tǐ", "body", "badan"],
    ["状态", "zhuàng tài", "condition", "keadaan"],
    ["不佳", "bù jiā", "poor", "tidak baik"],
    ["<br>", "", "", ""],
    ["或", "huò", "or", "atau"],
    ["路况", "lù kuàng", "road conditions", "keadaan jalan"],
    ["<br>", "", "", ""],
    ["而", "ér", "", ""],
    ["延误", "yán wù", "delayed", "terlewat"],
    ["<br>", "", "", ""],
    ["招致", "zhāo zhì", "drew", "mendapat"],
    ["订户", "dìng hù", "customers", "pelanggan"],
    ["的", "de", "", ""],
    ["埋怨", "mái yuàn", "complaints", "rungutan"],
    ["<br>", "", "", ""],
    ["满肚子", "mǎn dù zi", "full of", "penuh"],
    ["的", "de", "", ""],
    ["苦楚", "kǔ chǔ", "bitterness", "kepahitan"],
    ["<br>", "", "", ""],
    ["只能", "zhǐ néng", "could only", "hanya boleh"],
    ["化作", "huà zuò", "turn into", "menjadi"],
    ["一声", "yì shēng", "a", "satu"],
    ["叹息", "tàn xī", "sigh", "keluhan"],
    ["<br>", "", "", ""],
    ["他", "tā", "He", "Dia"],
    ["在", "zài", "in", "di"],
    ["风里", "fēng lǐ", "wind", "angin"],
    ["雨里", "yǔ lǐ", "rain", "hujan"],
    ["<br>", "", "", ""],
    ["风尘仆仆", "fēng chén pú pú", "travel-worn", "berdebu-debu"],
    ["<br>", "", "", ""],
    ["分不清", "fēn bù qīng", "couldn't tell", "tak dapat bezakan"],
    ["是", "shì", "", ""],
    ["汗", "hàn", "sweat", "peluh"],
    ["是", "shì", "", ""],
    ["雨", "yǔ", "rain", "hujan"],
    ["<br>", "", "", ""],
    ["无暇", "wú xiá", "no time", "tiada masa"],
    ["擦拭", "cā shì", "to wipe", "mengelap"],
    ["<br>", "", "", ""],
    ["依旧", "yī jiù", "still", "masih"],
    ["抖擞", "dǒu sǒu", "kept up", "bersemangat"],
    ["精神", "jīng shén", "spirits", "semangat"],
    ["<br>", "", "", ""],
    ["尽管", "jǐn guǎn", "Although", "Walaupun"],
    ["容颜", "róng yán", "face", "wajah"],
    ["憔悴", "qiáo cuì", "haggard", "lesu"],
    ["了", "le", "", ""],
    ["<br>", "", "", ""],
    ["身心", "shēn xīn", "body and mind", "badan dan minda"],
    ["疲惫", "pí bèi", "exhausted", "penat"],
    ["了", "le", "", ""],
    ["<br>", "", "", ""],
    ["也", "yě", "still", "tetap"],
    ["要", "yào", "must", "mesti"],
    ["规矩", "guī jǔ", "properly", "dengan teratur"],
    ["地", "de", "", ""],
    ["履行", "lǚ xíng", "perform", "melaksanakan"],
    ["职责", "zhí zé", "duties", "tugas"],
    ["<br>", "", "", ""],
    ["继续", "jì xù", "continued", "teruskan"],
    ["与", "yǔ", "with", "dengan"],
    ["时间", "shí jiān", "time", "masa"],
    ["追逐", "zhuī zhú", "chasing", "mengejar"],
    ["的", "de", "", ""],
    ["游戏", "yóu xì", "game", "permainan"],

    ["\n", "", "", ""], // 👈 第四节 → 第五节

    // ===== 第五节 =====
    ["温暖", "wēn nuǎn", "Warmth", "Kehangatan"],
    ["与", "yǔ", "and", "dan"],
    ["动力", "dòng lì", "Motivation", "Motivasi"],
    ["<br>", "", "", ""],
    ["一份", "yí fèn", "A", "Seporsi"],
    ["暖意融融", "nuǎn yì róng róng", "warm", "yang hangat"],
    ["的", "de", "", ""],
    ["餐点", "cān diǎn", "meal", "hidangan"],
    ["<br>", "", "", ""],
    ["一罐", "yí guàn", "A can of", "Se tin"],
    ["沁人心脾", "qìn rén xīn pí", "refreshing", "menyegarkan"],
    ["的", "de", "", ""],
    ["饮料", "yǐn liào", "drink", "minuman"],
    ["<br>", "", "", ""],
    ["一声声", "yì shēng shēng", "Repeated", "Berulang kali"],
    ["真诚", "zhēn chéng", "sincere", "ikhlas"],
    ["的", "de", "", ""],
    ["道谢", "dào xiè", "thanks", "terima kasih"],
    ["<br>", "", "", ""],
    ["家人", "jiā rén", "Family", "Keluarga"],
    ["熟睡", "shú shuì", "sleeping soundly", "nyenyak tidur"],
    ["的", "de", "", ""],
    ["面容", "miàn róng", "faces", "wajah"],
    ["<br>", "", "", ""],
    ["和", "hé", "and", "dan"],
    ["贴心", "tiē xīn", "caring", "penuh kasih"],
    ["的", "de", "", ""],
    ["关爱", "guān ài", "love", "sayang"],
    ["<br>", "", "", ""],
    ["是", "shì", "These are", "Inilah"],
    ["这些", "zhè xiē", "these", "ini"],
    ["日子", "rì zi", "days", "hari"],
    ["里", "lǐ", "in", "dalam"],
    ["<br>", "", "", ""],
    ["他", "tā", "his", "dia punya"],
    ["最大", "zuì dà", "greatest", "terbesar"],
    ["的", "de", "", ""],
    ["慰藉", "wèi jiè", "comfort", "penghiburan"],
    ["与", "yǔ", "and", "dan"],
    ["动力", "dòng lì", "motivation", "motivasi"],

    ["\n", "", "", ""], // 👈 第五节 → 第六节

    // ===== 第六节 =====
    ["希冀", "xī jì", "Hope", "Harapan"],
    ["<br>", "", "", ""],
    ["落寞", "luò mò", "Loneliness", "Kesunyian"],
    ["、", "", "", ""],
    ["徘徊", "pái huái", "hesitation", "keraguan"],
    ["、", "", "", ""],
    ["焦虑", "jiāo lǜ", "anxiety", "keresahan"],
    ["<br>", "", "", ""],
    ["不复存在", "bù fù cún zài", "no longer exist", "tidak wujud lagi"],
    ["<br>", "", "", ""],
    ["他", "tā", "His", "Dia punya"],
    ["奔驰", "bēn chí", "racing", "membanting"],
    ["于", "yú", "on", "di"],
    ["路上", "lù shàng", "the road", "jalan"],
    ["的", "de", "", ""],
    ["汗水", "hàn shuǐ", "sweat", "peluh"],
    ["<br>", "", "", ""],
    ["不会", "bù huì", "will not", "tidak akan"],
    ["白费", "bái fèi", "be in vain", "sia-sia"],
    ["<br>", "", "", ""],
    ["他", "tā", "He", "Dia"],
    ["祈愿", "qí yuàn", "prays", "berdoa"],
    ["人们", "rén men", "people", "manusia"],
    ["<br>", "", "", ""],
    ["因为", "yīn wèi", "Because of", "Kerana"],
    ["关怀", "guān huái", "care", "keprihatinan"],
    ["<br>", "", "", ""],
    ["彼此", "bǐ cǐ", "each other", "satu sama lain"],
    ["更", "gèng", "more", "lebih"],
    ["愿意", "yuàn yì", "willing", "rela"],
    ["释出", "shì chū", "show", "menunjukkan"],
    ["善意", "shàn yì", "kindness", "kebaikan"],
    ["<br>", "", "", ""],
    ["因为", "yīn wèi", "Because of", "Kerana"],
    ["包容", "bāo róng", "tolerance", "toleransi"],
    ["<br>", "", "", ""],
    ["大家", "dà jiā", "everyone", "semua orang"],
    ["携手", "xié shǒu", "join hands", "berganding bahu"],
    ["同心", "tóng xīn", "with one heart", "sehati sejiwa"],
    ["<br>", "", "", ""],
    ["跨越", "kuà yuè", "cross", "mengharungi"],
    ["焦躁", "jiāo zào", "anxiety", "keresahan"],
    ["的", "de", "", ""],
    ["隔阂", "gé hé", "barriers", "jurang"],
    ["<br>", "", "", ""],
    ["一同", "yì tóng", "together", "bersama"],
    ["迈向", "mài xiàng", "step towards", "melangkah ke arah"],
    ["<br>", "", "", ""],
    ["繁荣", "fán róng", "prosperity", "kemakmuran"],
    ["昌盛", "chāng shèng", "flourishing", "kesejahteraan"],
    ["<br>", "", "", ""],
    ["更", "gèng", "more", "lebih"],
    ["具", "jù", "with", "mempunyai"],
    ["同理心", "tóng lǐ xīn", "empathy", "empati"],
    ["的", "de", "", ""],
    ["社会", "shè huì", "society", "masyarakat"],

    ["\n", "", "", ""], // 👈 第六节 → 出处

    // ===== 出处 =====
    ["（", "", "", ""],
    ["佚名", "yì míng", "Anonymous", "Tanpa Nama"],
    ["《", "", "", ""],
    ["奔驰在路上的汗水", "bēn chí zài lù shàng de hàn shuǐ", "Sweat on the Road", "Peluh di Jalan"],
    ["》", "", "", ""],
    ["，", "", "", ""],
    ["有", "yǒu", "with", "ada"],
    ["改动", "gǎi dòng", "adaptations", "ubah suai"],
    ["）", "", "", ""]
];
